### ISSUE TITLE
Add support for ND response.

### ISSUE THREAD

**Issue by cleveremote** [101100/xbee-rx#13]
First of all thank you for your nice work.

I would add a support for ND command, because when execute ND (node discovery) the response instead of having commandData, it has nodeIdentification.

in function _sendFrameStreamResponse
```javascript
 if (frame.commandStatus === xbee_api.constants.COMMAND_STATUS.OK) {
    // return commandData; before
    return frame.command === "ND" ? frame.nodeIdentification : commandData;
 }
```

**Comment by 101100** [comment]
The trick there is that while other commands return a single value, a node discovery command could produce many and the timeout is configurable.  You can do a node discovery using the existing parts of the library, though.  There is an example program (I've highlighted the relevant part) here:

https://github.com/101100/xbee-rx/blob/248edb7e82dba41c0e352feffa952581d7967253/examples/node-discovery.js#L32-L61

This is a complete example, but might be more complex than you need as it reads the timeout (stored in `NT` as two bytes representing 1/10 seconds) and then waits exactly that amount of time.  Here is a simplified version when you already know the timeout:

```js
// default value of NT is 60 -> 6 seconds
var timeoutMs = 60000;

rx
    .merge(
        // create a stream of ND responses
        xbee.allPackets.pipe(
            rx.operators.filter(function (packet) {
                return packet.type === xbee_api.constants.FRAME_TYPE.AT_COMMAND_RESPONSE
                    && packet.command === "ND"; }),
            rx.operators.pluck("nodeIdentification")
            rx.operators.takeUntil(rx.timer(timeoutMs + 1000))),
        // send the ND command to trigger the responses
        xbee
            .localCommand({ command: "ND" })
            .pipe(
                // ND produces an error if it finds no nodes, so we ignore the error here
                rx.operators.catchError(function() { return rx.empty(); }),
                rx.operators.ignoreElements())
    )
    .subscribe(function (nodeIdentification) {
        console.log("Found node:\n", nodeIdentification);
    });
```

**Comment by cleveremote** [comment]
Thank you very much, this is a perfect example & exactly what I need.
