### ISSUE TITLE
Upgrade serialport to support newer kernels

### ISSUE THREAD

**Issue by MarcoTomasRodriguez** [101100/xbee-rx#16]
Hello,
I would like to thank you for developing and maintaining this package, we have been using it for a long time in production without any major issues.
But recently we wanted to upgrade from Raspbian w/ Debian 9 (Kernel 4.19) to Raspberry Pi OS w/ Debian 10 (Kernel 5.4), and suddenly it stopped sending data through the serial port.
I think that an update is required in the serialport library in order to support newer kernels, this project currently uses v6.0 and the latest is v9.0.2.
Thank you very much once again.

**Comment by 101100** [comment]
I can look into this this weekend.  If you would like, though, I would accept a pull request to make this change sooner.

**Comment by MarcoTomasRodriguez** [comment]
I will close the issue for now. If the same problem occurs, I will reopen it. Thank you very much sir.
