### ISSUE TITLE
great work but  !

### ISSUE THREAD

**Issue by ibrahimuslu** [101100/xbee-rx#2]
That is really great work but i can not figure out how to manage my problem. 

I am sending transmit request to receiving node.  after getting transmit ok message i have to get another message from recieving node to understand the status. The receiving node sends it but i can not get it. 

Could you please help me?

**Comment by 101100** [comment]
I'm not 100% sure what you are trying to do, but if you only want to send a transmission and then wait for a response from another module, you'll need to set it up kind of in reverse:

``` js
// listen for response (first so we don't miss the reply)
xbee
    .monitorTransmissions()
    .take(1) // we only want one reply (this means we don't need to .dispose() the subscription)
    .timeout(10000) // (optional) this line will cause an error if no response is head in 10 seconds
    .subscribe(function (transmissionPacket) {
        // check that it is from the correct module?
        console.log("Got response:", transmissionPacket.data);
    }, function (e) {
        // handle error in received packet (timeout
        console.log("No received packet:\n", e);
    });

// send packet
xbee.remoteTransmit({
    // this ID must be set on the target node with ATNI
    destinationId: "FUNNODE",
    data: "I'm sending you text, FUNNODE!"
}).subscribe(function () {
    // no problem
}, function (e) {
    // handle error in sent packet
    console.log("Send failed:\n", e);
});
```

Each of the xbee commands create an RxJS observable, which can be manipulated using the methods shown [here](https://github.com/Reactive-Extensions/RxJS/blob/master/doc/api/core/observable.md).

**Comment by 101100** [comment]
Closing due to no replies.
