### ISSUE TITLE
Unable to forward the output console.log to other Node

### ISSUE THREAD

**Issue by juancreyes** [101100/xbee-rx#3]
I am using your library xbee-rx in Node-Red project, temperature sensor through Xbee, where trying to inject the output to next node (debug-output) but I am unable to commit it. Specifically I have used temperature.js script as reference and after adapt to my environment (raspberryPi2) as per below with extra entry xbee.close() in first subscriber statement to avoid monitoring loop in background I can get temperature value in my Linux console but not in Node-Red.

``` js
var subscription = xbee
    .monitorIODataPackets()
    .pluck("analogSamples")
    .pluck("AD3") // extract just the AD3 sample (in millivolts)
    .map(function (mv) { return (mv) / 10; }) // convert millivolts to Centigrade
    .subscribe(function (value) {
        console.log(new Date(), "temperature:", value);
       xbee.close();
     }, function (error) {
        console.log("Error during monitoring:\n", error);
        xbee.close();
     });
node.error("Error");
return (msg);
```

I am new with RxJS method and would like your help in this matter, Can you advice how to manage console.log data output and be capable to use as msg.payload, object or buffer in order to forward to next node ?.

**Comment by 101100** [comment]
You can't easily capture the `console.log` output, but you can call `node.send` inside the `subscribe`.

Also, to take just one sample, but leave the serial port open for future packets, you can use `.take(1)` at some point before `subscribe`.

It seems that nodes can have a `close` function, so that seems like the better place for `xbee.close()`.

I've never used Node-Red before, so I didn't adjust your example to make it into an injector node.  I left it as one in the middle of a stream, so you will need to send it something before it will read the temperature.  Based on the example for [first node](http://nodered.org/docs/creating-nodes/first-node), you could do something like:

``` js
module.exports = function (RED) {
    function XbeeTemperatureNode(config) {
        RED.nodes.createNode(this, config);

        var node = this;

        // create xbee variable here so it can be shared over all the temperature readings
        var xbee = ...

        this.on('input', function(msg) {
            // when this node gets input, it will output a temperature reading (ignoring the input)
            xbee
                .monitorIODataPackets()
                .take(1) // only take one packet
                .pluck("analogSamples")
                .pluck("AD3") // extract just the AD3 sample (in millivolts)
                .map(function (mv) { return (mv) / 10; }) // convert millivolts to Centigrade
                .subscribe(function (value) {
                    console.log("Sending temperature:", value);
                    node.send(value);
                }, function (error) {
                    // this seems to be the way to properly error from a node
                    node.error("Error with XBee", error);
                });
        });

        // when this node gets the close signal from Node-Red, close the xbee (and the serial port)
        this.on("close", function closeXbee() {
            xbee.close();
        };
    }

    RED.nodes.registerType("xbee-temp", XbeeTemperatureNode);
}
```

Hope this helps.

**Comment by juancreyes** [comment]
Hi there,

I am using following flow wired: Inject_Input + function(f) + Debug_Output. I tested your approach and other one with small change using msg.payload and not success in Debug_output, I am not seeing nothing in debug ouput and linux shell doesn't show console output neither. It supposes each time click in Inject, it triggers to function(f) node to start working and node.send(value) should pass the messages to next node (Debug_Output). There is a Node-red guide which show details, http://noderedguide.com, you may understand quicker than me. If you have time please feedback. Meanwhile I will ask in node-red group to see what is missing or wrong.

The function node looks like: 

```
    // start function
          function XbeeTemperatureNode(config) {
          RED.nodes.createNode(this, config);
          var node = this;
    // create xbee variable here so it can be shared over all the temperature readings
    var xbeeRx = context.global.xbeeRx;
    var xbee = xbeeRx({
        serialport:'/dev/ttyAMA0',
        serialPortOptions:{
        baudrate: 9600 },
        module: "ZigBee",
     // turn on debugging to see what the library is doing
        debug: false
});

    this.on('input', function(msg) {
        // when this node gets input, it will output a temperature reading (ignoring the input)
        xbee
            .monitorIODataPackets()
            .take(1) // only take one packet
            .pluck("analogSamples")
            .pluck("AD3") // extract just the AD3 sample (in millivolts)
            .map(function (mv) { return (mv) / 10; }) // convert millivolts to Centigrade
            .subscribe(function (value) {
             console.log("Sending temperature:", value);
             msg.payload ="Temp is" + value;  // second appoach.
     node.send(msg);                            // change argument to test above variable.
            }, function (error) {
                // this seems to be the way to properly error from a node
                node.error("Error with XBee", error);
            });
    });
    // when this node gets the close signal from Node-Red, close the xbee (and the serial port)
    this.on("close", function closeXbee() {
        xbee.close():
    });
    }
```

I removed "The function (RED)" because got error with module.export and looks doesn't apply to functions node. 

Regards.-
jcr

**Comment by 101100** [comment]
Are you using a function node?  If so, that is your problem.  The function node needs to return a value when it runs, but the XBee won't necessarily have a packet at that instant and that is why you have to call `subscribe`.  Returning a value inside the `subscribe` function won't get that data back to Node-Red though, so that is why it isn't working.

**Comment by juancreyes** [comment]
Yes, I am using function node. So through Node-red flavor which predefined node do you suggest to commit above ?. or basically I should go to create a customized one ?.

Regards
Juan

**Comment by 101100** [comment]
Actually, I've played with it a bit more and async does work (the documentation wasn't clear).  I'm not sure how you are getting an npm module into Node-Red (where does `context.global.xbeeRx` come from?), but if that part works, this should work:

``` js
var xbee = context.get("xbee");
if (!xbee) {
    // create xbee variable and store it in the global context so it doesn't need to be created over and over again
    node.log("Making xbee...");
    var xbeeRx = context.global.xbeeRx;
    xbee = xbeeRx({
        serialport:'/dev/ttyAMA0',
        serialPortOptions: { baudrate: 9600 },
        module: "ZigBee"
    });
    context.set("xbee", xbee);
}

// when this node's function is called, it will output a temperature reading (ignoring the input)
xbee
    .monitorIODataPackets()
    .take(1) // only take one packet
    .pluck("analogSamples")
    .pluck("AD3") // extract just the AD3 sample (in millivolts)
    .map(function (mv) { return (mv) / 10; }) // convert millivolts to Centigrade
    .subscribe(function (value) {
        node.log("Sending value:", value)
        node.send({ payload: value });
    }, function (error) {
        // this seems to be the way to properly error from a node
        node.error("Error with XBee", error);
    });

// when this node gets the close signal from Node-Red, close the xbee (and the serial port)
node.on("close", function closeXbee() {
    xbee.close();
};

return null;
```

**Comment by juancreyes** [comment]
I defined context.global.xbeeRx in settings.js conf file of Nodered as functionGlobalContext. It is part of sandboxing concept among of Nodered tool. More reference,  http://nodered.org/docs/configuration.

I will test new code later and will let you now.

Thanks and regards.

**Comment by juancreyes** [comment]
Hi master,
          You betted it. It works, the output came up in debug panel each time press injector bottom. 25,8 is actually Celsius degree. The first condition to avoid over create the context is awesome.

Debug tag:
   msg : Object
   { "payload": 25.8, "_msgid": "23000532.7d4fa6" }

Also in linux console show up the log.

```
[info] [function:Function Xbee] Sending value: '**
```

Now I can move forward. I really appreciate your help. I have to continue learning about JS, npm, node-red.

Thanks a lot.
Regards.

**Comment by 101100** [comment]
Glad I could help.  I'm going to close this issue since it is working for you now.
